### ISSUE TITLE
Design tasks

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Non-Tech-Tasks#1]
- Design Social media material
- Design logo
- Design an official website

**Comment by Tassyomah** [comment]
@tapaswenipathak  For the logo, what kind of logo do you want?

Just an official website for any company,  or are there other requirements that should be inclusive in the website ?
I need more details so i don't design something different.

**Comment by tapaswenipathak** [comment]
On Thu, May 23, 2019 at 5:48 PM Tassyomah <notifications@github.com> wrote:
>
> @tapaswenipathak what kind of logo do you want?

Think of Alice in mind, do you know
https://en.wikipedia.org/wiki/Alice%27s_Adventures_in_Wonderland. Add
computery Alice in wonderland.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by Tassyomah** [comment]
Okay I've seen the link.

 You want the likes of that cover picture? Tagged Computery Alice in wonderland?

**Comment by tapaswenipathak** [comment]
Please be creative, doing what you feel like and put up the designs.

**Comment by Tassyomah** [comment]
![Untitled-7](https://user-images.githubusercontent.com/39609142/58418844-e1902400-8080-11e9-8484-b09c696a5436.jpg)

**Comment by tapaswenipathak** [comment]
Thanks for the work. Few things

- A lot of black/darkish color
- No computer
- I would love tinge of orange color hex code #FFA500

**Comment by Tassyomah** [comment]
!
![task1](https://user-images.githubusercontent.com/39609142/58440438-f8129b80-80d1-11e9-818f-ca7abfdf24ab.jpg)

**Comment by Tassyomah** [comment]
![task2](https://user-images.githubusercontent.com/39609142/58440507-60617d00-80d2-11e9-8561-f35870d7a568.jpg)

**Comment by tapaswenipathak** [comment]
Can you add a computer logo or image instead of writing the word? I think you have picked the pic from the movie.

**Comment by Tassyomah** [comment]
I don't understand what you mean ma'am.  How do you mean by a computer logo or image?
I didn't pick the pic from the movie, this is an image i got online and edited it myself.

**Comment by Tassyomah** [comment]
@tapaswenipathak I need more clarifications please.

**Comment by bymayanksingh** [comment]
@tapaswenipathak are they good?
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968065-0e850900-9551-11e9-8f3d-6fa64379e5b7.png)
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968066-10e76300-9551-11e9-8ec3-263f35220143.png)
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968067-15ac1700-9551-11e9-824f-f3b73a71f6b8.png)
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968068-15ac1700-9551-11e9-9789-17b74e52d299.png)
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968069-15ac1700-9551-11e9-8bf4-2382f7455d94.png)
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968070-1644ad80-9551-11e9-8bda-604bf3ae2a31.png)
![Screenshot_2019-06-23](https://user-images.githubusercontent.com/19390263/59968071-1644ad80-9551-11e9-802b-b8b112e99d6b.png)

**Comment by bymayanksingh** [comment]
![Untitled-1](https://user-images.githubusercontent.com/19390263/59980950-a995e580-961a-11e9-9fe0-37a141195505.jpg)

@tapaswenipathak take a look.

**Comment by code-monk08** [comment]
![Background](https://user-images.githubusercontent.com/19390263/59981717-5ecd9b00-9625-11e9-906d-cc5c2a1b3333.png)
![Background](https://user-images.githubusercontent.com/19390263/59981718-5ffec800-9625-11e9-83b6-93000a081480.png)

**Comment by code-monk08** [comment]
![Background(2)](https://user-images.githubusercontent.com/19390263/59981819-c9cba180-9626-11e9-86ff-4ef71da4f8cd.png)

**Comment by bymayanksingh** [comment]
![Background(3)](https://user-images.githubusercontent.com/19390263/59981824-e49e1600-9626-11e9-8c83-e7f103e9bb68.png)

**Comment by bymayanksingh** [comment]
this one without the circular outline.
![sieve](https://user-images.githubusercontent.com/19390263/60115809-665f8200-9794-11e9-9720-2b4045ee2b90.png)
this one with a device.
![w device](https://user-images.githubusercontent.com/19390263/60115812-66f81880-9794-11e9-9561-6a83946a1de2.png)

**Comment by tapaswenipathak** [comment]
Thanks @Tassyomah and @code-monk08 for the effort.
